testWebApi/Controllers/Api/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using ModeloPedidos.Clases;
using ModeloPedidos.Clases.DAOs;
using ModeloPedidos.Clases.DTOs;

namespace testWebApi.Controllers.Api
{
    public class PedidosController : ApiController
    {
        private PruebasEntities db = new PruebasEntities();

        // GET: api/Pedidos
        public IHttpActionResult GetPedidos(string current, string rowCount, string searchPhrase, string id)
        {
            /*
             * Formato de la peticion que realiza por ajax el bootgrid
             current=1 & rowCount=10 & sort[sender]=asc & searchPhrase= & id=b0df282a-0d67-40e5-8558-c9e93b7befed

             */

            int iCurrent = 1;
            int iRowCount = 10;
            int iTotalRegistros = 0;
            string campoOrdenar = string.Empty;
            string orden = string.Empty;

            // obtiene de los parametros del query string el campo y el sentido de ordenacion
            var vars = Request.GetQueryNameValuePairs();

            KeyValuePair<string, string> sortValues = vars.FirstOrDefault(x => x.Key.Contains("sort"));

            if (!string.IsNullOrEmpty(sortValues.Value))
            {
                campoOrdenar = sortValues.Key.TrimStart("sort.".ToArray());
                orden = sortValues.Value;
            }

            // se transforman los valores de paginación
            Int32.TryParse(current, out iCurrent);
            Int32.TryParse(rowCount, out iRowCount);

            // obtiene la lista de familias filtrada
            PedidosDAO item = new PedidosDAO();
            List<PedidoDTO> lista = new List<PedidoDTO>();

            lista = item.GetListaFiltrada(iCurrent, iRowCount, searchPhrase, campoOrdenar, orden, out iTotalRegistros);

            // se completa el objeto de respuesta
            DataBootGrid bootGrid = new DataBootGrid()
            {
                current = iCurrent,
                rowsCount = iRowCount,
                rows = lista.ToArray(),
                total = iTotalRegistros
            };

            return Ok(bootGrid);
        }


        // GET: api/Pedidos/5
        [ResponseType(typeof(Pedidos))]
        public IHttpActionResult GetPedidos(int id)
        {
            Pedidos pedidos = db.Pedidos.Find(id);
            if (pedidos == null)
            {
                return NotFound();
            }

            return Ok(pedidos);
        }

        // PUT: api/Pedidos/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutPedidos(int id, Pedidos pedidos)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != pedidos.Id_pedido)
            {
                return BadRequest();
            }

            db.Entry(pedidos).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PedidosExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Pedidos
        [ResponseType(typeof(Pedidos))]
        public IHttpActionResult PostPedidos(Pedidos pedidos)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Pedidos.Add(pedidos);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = pedidos.Id_pedido }, pedidos);
        }

        // DELETE: api/Pedidos/5
        [ResponseType(typeof(Pedidos))]
        public IHttpActionResult DeletePedidos(int id)
        {
            Pedidos pedidos = db.Pedidos.Find(id);
            if (pedidos == null)
            {
                return NotFound();
            }

            db.Pedidos.Remove(pedidos);
            db.SaveChanges();

            return Ok(pedidos);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool PedidosExists(int id)
        {
            return db.Pedidos.Count(e => e.Id_pedido == id) > 0;
        }
    }
}

testWebApi/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ModeloPedidos.Clases;

namespace testWebApi.Controllers
{
    public class PedidosController : Controller
    {
        private PruebasEntities db = new PruebasEntities();

        // GET: Pedidos
        public ActionResult Index()
        {
            var pedidos = db.Pedidos.Include(p => p.Personas).Include(p => p.Restaurantes);
            return View(pedidos.ToList());
        }

        // GET: Pedidos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedidos pedidos = db.Pedidos.Find(id);
            if (pedidos == null)
            {
                return HttpNotFound();
            }
            return View(pedidos);
        }

        // GET: Pedidos/Create
        public ActionResult Create()
        {
            ViewBag.FIdPersona = new SelectList(db.Personas, "id", "nombre");
            ViewBag.FIdRestaurante = new SelectList(db.Restaurantes, "Id_Restaurante", "Restaurante");
            return View();
        }

        // POST: Pedidos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_pedido,Referencia,Fecha,FIdRestaurante,FIdPersona")] Pedidos pedidos)
        {
            if (ModelState.IsValid)
            {
                db.Pedidos.Add(pedidos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FIdPersona = new SelectList(db.Personas, "id", "nombre", pedidos.FIdPersona);
            ViewBag.FIdRestaurante = new SelectList(db.Restaurantes, "Id_Restaurante", "Restaurante", pedidos.FIdRestaurante);
            return View(pedidos);
        }

        // GET: Pedidos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedidos pedidos = db.Pedidos.Find(id);
            if (pedidos == null)
            {
                return HttpNotFound();
            }
            ViewBag.FIdPersona = new SelectList(db.Personas, "id", "nombre", pedidos.FIdPersona);
            ViewBag.FIdRestaurante = new SelectList(db.Restaurantes, "Id_Restaurante", "Restaurante", pedidos.FIdRestaurante);
            return View(pedidos);
        }

        // POST: Pedidos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_pedido,Referencia,Fecha,FIdRestaurante,FIdPersona")] Pedidos pedidos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pedidos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FIdPersona = new SelectList(db.Personas, "id", "nombre", pedidos.FIdPersona);
            ViewBag.FIdRestaurante = new SelectList(db.Restaurantes, "Id_Restaurante", "Restaurante", pedidos.FIdRestaurante);
            return View(pedidos);
        }

        // GET: Pedidos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedidos pedidos = db.Pedidos.Find(id);
            if (pedidos == null)
            {
                return HttpNotFound();
            }
            return View(pedidos);
        }

        // POST: Pedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pedidos pedidos = db.Pedidos.Find(id);
            db.Pedidos.Remove(pedidos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

testWebApi/Controllers/ProductosPedidosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ModeloPedidos.Clases;

namespace testWebApi.Controllers
{
    public class ProductosPedidosController : Controller
    {
        private PruebasEntities db = new PruebasEntities();

        [ChildActionOnly]
        public ActionResult _listaProductosPedido(int? idPedido)
        {
            var lista = db.ProductosPedidos.Where(x => x.FIdPedido == idPedido).ToList();
            return PartialView("_listaProductosPedido", lista);
        }
        
        // GET: ProductosPedidos
        public ActionResult Index()
        {
            var productosPedidos = db.ProductosPedidos.Include(p => p.Productos);
            return View(productosPedidos.ToList());
        }

        // GET: ProductosPedidos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductosPedidos productosPedidos = db.ProductosPedidos.Find(id);
            if (productosPedidos == null)
            {
                return HttpNotFound();
            }
            return View(productosPedidos);
        }

        // GET: ProductosPedidos/Create
        public ActionResult Create()
        {
            ViewBag.FIdProducto = new SelectList(db.Productos, "Id_prod", "Nombre_prod");
            return View();
        }

        // POST: ProductosPedidos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_productosPedido,FIdPedido,FIdProducto,Cantidad")] ProductosPedidos productosPedidos)
        {
            if (ModelState.IsValid)
            {
                db.ProductosPedidos.Add(productosPedidos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FIdProducto = new SelectList(db.Productos, "Id_prod", "Nombre_prod", productosPedidos.FIdProducto);
            return View(productosPedidos);
        }

        // GET: ProductosPedidos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductosPedidos productosPedidos = db.ProductosPedidos.Find(id);
            if (productosPedidos == null)
            {
                return HttpNotFound();
            }
            ViewBag.FIdProducto = new SelectList(db.Productos, "Id_prod", "Nombre_prod", productosPedidos.FIdProducto);
            return View(productosPedidos);
        }

        // POST: ProductosPedidos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_productosPedido,FIdPedido,FIdProducto,Cantidad")] ProductosPedidos productosPedidos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productosPedidos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FIdProducto = new SelectList(db.Productos, "Id_prod", "Nombre_prod", productosPedidos.FIdProducto);
            return View(productosPedidos);
        }

        // GET: ProductosPedidos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductosPedidos productosPedidos = db.ProductosPedidos.Find(id);
            if (productosPedidos == null)
            {
                return HttpNotFound();
            }
            return View(productosPedidos);
        }

        // POST: ProductosPedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductosPedidos productosPedidos = db.ProductosPedidos.Find(id);
            db.ProductosPedidos.Remove(productosPedidos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

testWebApi/Views/Pedidos/Create.cshtml
@model ModeloPedidos.Clases.Pedidos

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pedidos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Referencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Referencia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Referencia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FIdRestaurante, "FIdRestaurante", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FIdRestaurante", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FIdRestaurante, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FIdPersona, "FIdPersona", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FIdPersona", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FIdPersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

testWebApi/Views/Pedidos/Delete.cshtml
@model ModeloPedidos.Clases.Pedidos

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pedidos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Referencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Referencia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Personas.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Personas.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Restaurantes.Restaurante)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurantes.Restaurante)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

testWebApi/Views/Pedidos/Details.cshtml
@model ModeloPedidos.Clases.Pedidos

@{
    ViewBag.Title = "Detalle del Pedido";
}

<h2>Detalle del Pedido</h2>
<div>
    <hr />
    <div class="alert alert-info">
        <div class="container">
            <div class="row p-b-10">
                <div class="col-md-3">
                    <div class="row">
                        <div class="col-md-6 negrita text-left">@Html.DisplayNameFor(model => model.Restaurantes.Restaurante)</div>
                        <div class="col-md-6 text-left">@Html.DisplayFor(model => model.Restaurantes.Restaurante)</div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="row">
                        <div class="col-md-6 negrita text-left">@Html.DisplayNameFor(model => model.Referencia)</div>
                        <div class="col-md-6 text-left">@Html.DisplayFor(model => model.Referencia)</div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="row">
                        <div class="col-md-6 negrita text-left">@Html.DisplayNameFor(model => model.Fecha)</div>
                        <div class="col-md-6 text-left">@Html.DisplayFor(model => model.Fecha)</div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="row">
                        <div class="col-md-6 negrita text-left">@Html.DisplayNameFor(model => model.Personas.nombre)</div>
                        <div class="col-md-6 text-left">@Html.DisplayFor(model => model.Personas.nombre)</div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
@{
    Html.RenderAction("_listaProductosPedido", "ProductosPedidos", new { idPedido = Model.Id_pedido });

}
<p class="text-right">
    @Html.ActionLink("Nuevo Producto", "Create", "ProductosPedidos", new { id = Model.Id_pedido, @class = "btn btn-primary" })
    @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-default"})
</p>

testWebApi/Views/Pedidos/Edit.cshtml
@model ModeloPedidos.Clases.Pedidos

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pedidos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_pedido)

        <div class="form-group">
            @Html.LabelFor(model => model.Referencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Referencia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Referencia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FIdRestaurante, "FIdRestaurante", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FIdRestaurante", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FIdRestaurante, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FIdPersona, "FIdPersona", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FIdPersona", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FIdPersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

testWebApi/Views/Pedidos/Index.cshtml
@{
    ViewBag.Title = "Pedidos";
}


<h2>Pedidos</h2>
<hr />

<table id="gvPedidos" class="table table-condensed table-hover table-striped">
    <thead>
        <tr>
            <th data-column-id="Id_pedido" data-type="numeric">ID</th>
            <th data-column-id="Referencia">Referencia</th>
            <th data-column-id="Fecha">Fecha</th>
            <th data-column-id="NombreRestaurante">Restaurante</th>
            <th data-column-id="NombrePersona">Pedido Por</th>
            <th data-column-id="commands" data-formatter="commands" data-sortable="false">Acciones</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>

    </tbody>
</table>

@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            var grid = $("#gvPedidos").bootgrid({
                ajax: true,
                rowselect: true,
                ajaxSettings: {
                    method: "GET",
                    cache: false
                },
                post: function () {
                    return {
                        id: "D5DEF094-CACD-423C-B990-4154778BD085"
                    };
                },
                url: "/api/Pedidos",
                searchSettings: {
                    delay: 1000,
                    characters: 3
                },
                labels: {
                    all: "ALL",
                    infos: "Este es el listado de pedidos",
                    loading: "Obteniendo datos ...",
                    noResults: "Ups!! No hay resultados",
                    refresh: "Recargar los datos",
                    search: "buscar..."
                },
                formatters: {
                    "commands": function (column, row) {
                        return "<a class='btn btn-primary btn-xs' href='/Pedidos/Details/"
                            + row.Id_pedido + "' >Detalle</a>  &nbsp; " +
                            "<a class='btn btn-warning btn-xs' href='/Pedidos/Edit/"
                            + row.Id_pedido + "' >Editar</a> &nbsp; "
                            + "<a class='btn btn-danger btn-xs' href='/Pedidos/Delete/"
                            + row.Id_pedido + "' >Eliminar</a>"
                    }
                }
            });
        });
    </script>
}